#!/usr/bin/env python

# Check out jQuery Tools and jquery from from source repositories;
# run jslint, minify and repackage into plone.app.jquerytools
# resources.
#
# Uses Google's closure compiler for the minification.
#
# Added to p.a.jqt by Rok Garbas


import os
import shlex
import shutil
import urllib2
import tarfile
import tempfile
import StringIO
import subprocess
import datetime

JQ_TOOLS_VERSION = 'v1.2.7'
JQ_TOOLS_DOWNLOAD_URL = 'http://github.com/jquerytools/jquerytools/tarball/'+JQ_TOOLS_VERSION

JQ_FORM_VERSION = 'master' # there is no tag
JQ_FORM_URL= 'http://github.com/malsup/form/tarball/'+JQ_FORM_VERSION


def run_hooks(name, hooks, kw):
    if name in hooks.keys():
        for hook in hooks[name]:
            kw = hook(**kw)
    return kw

def build(name, download_url, hooks=dict(), **kw):

    kw['name'] = name
    kw['download_url'] = download_url

    # create temporary directory
    kw['tmp_dir'] = tempfile.mkdtemp(prefix='build--'+name)

    # download the archive
    archive = urllib2.urlopen(download_url).fp.read()
    f = StringIO.StringIO()
    f.write(archive)
    f.seek(0)

    # extract it to temporary folder
    archive_tar = tarfile.open(fileobj=f)
    for member in archive_tar.getmembers():
        if member.path.startswith('/') or \
           member.path.startswith('..'):
            raise Exception('Somebody wants to harm your coputer.')
    archive_tar.extractall(kw['tmp_dir'])
    f.close()

    try:

        # defaults
        out = os.listdir(kw['tmp_dir'])
        if len(out) != 1:
            raise Exception('There should only be one folder')

        kw['source_dir_name'] = out[0]
        kw['source_dir'] = os.path.join(kw['tmp_dir'], kw['source_dir_name'])
        kw['build_dir'] = os.path.join(kw['tmp_dir'], kw['source_dir_name']+'-build')

        # before hooks
        kw = run_hooks('before', hooks, kw)

        for dirpath, dirnames, filenames in os.walk(kw['build_dir']):
            for filename in filenames:
                kw['filename'] = os.path.join(dirpath, filename)
                kw['short_filename'] = kw['filename'][len(kw['build_dir']) + 1:]

                print '-' * 80
                print 'FILE: ' + kw['short_filename']

                # per_file hooks
                kw = run_hooks('per_file', hooks, kw)

        # after hooks
        kw = run_hooks('file', hooks, kw)

    finally:

        # remove temporary directory
        shutil.rmtree(kw['tmp_dir'])


def main():
    """
        master plan:
         * pull version from http://github.com/jquerytools/jquerytools/tarball/v${VERSION}
         * untar and make usual build it like ant is doing it (look build.xml)
         * merge files like its is done in README.txt and copy it to plone/app/jquerytools/browser folder
    """

    # TODO: we could make get values bellow bia sys.args (argparse)


    PLONE_MAPPING = {
        'jquery.tools.js': [
                'jquery.tools:overlay/overlay.js',
                'jquery.tools:scrollable/scrollable.js',
                'jquery.tools:tabs/tabs.js',
                'jquery.tools:toolbox/toolbox.history.js',
                'jquery.tools:toolbox/toolbox.expose.js',
                'jquery.tools:tooltip/tooltip.js',
            ],
        'jquery.tools.plugins.js': [
                'jquery.tools:overlay/overlay.apple.js',
                'jquery.tools:scrollable/scrollable.autoscroll.js',
                'jquery.tools:scrollable/scrollable.navigator.js',
                'jquery.tools:tabs/tabs.slideshow.js',
                'jquery.tools:toolbox/toolbox.flashembed.js',
                'jquery.tools:toolbox/toolbox.mousewheel.js',
                'jquery.tools:tooltip/tooltip.dynamic.js',
                'jquery.tools:tooltip/tooltip.slide.js',
            ],
        'jquery.tools.dateinput.css': [
                'jquery.tools:dateinput/skin1.css',
            ],
        'jquery.tools.dateinput.js': [
                'jquery.tools:dateinput/dateinput.js',
            ],
        'jquery.tools.rangeinput.js': [
                'jquery.tools:rangeinput/rangeinput.js',
            ],
        'jquery.tools.validator.js': [
                'jquery.tools:validator/validator.js',
            ],
        'jquery.form.js': [
                'jquery.form:jquery.form.js',
                ]
    }

    #
    # run build for all libs
    build('jquery.tools', JQ_TOOLS_DOWNLOAD_URL,
          version=JQ_TOOLS_VERSION,
          plone_mapping=PLONE_MAPPING,
          today=datetime.datetime.today().strftime("%Y-%m-%d %H:%M"),
          jslint=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'jslint.js'),
          rhino=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'rhino.jar'),
          compiler=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'compiler.jar'),
          plone_dir=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'plone', 'app', 'jquerytools', 'browser'),
          hooks = {'before': [
                        jq_tools_before_hook,
                        plone_before_hook],
                   'per_file': [
                        version_hook,
                        date_hook,
                        lint_hook,
                        minify_hook,
                        plone_file_hook],
                  })
    build('jquery.form', JQ_FORM_URL,
          plone_mapping=PLONE_MAPPING,
          today=datetime.datetime.today().strftime("%Y-%m-%d %H:%M"),
          jslint=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'jslint.js'),
          rhino=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'rhino.jar'),
          compiler=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib', 'compiler.jar'),
          plone_dir=os.path.join(os.path.abspath(os.path.dirname(__file__)), 'plone', 'app', 'jquerytools', 'browser'),
          hooks = {'before': [
                        jq_form_before_hook,
                        plone_before_hook],
                   'per_file': [
                        lint_hook,
                        minify_hook,
                        plone_file_hook],
                  })


def jq_tools_before_hook(**kw):
    shutil.copytree(
            os.path.join(kw['source_dir'], 'src'),
            kw['build_dir'])

    # FIXME: this should actually copy all *.js files from lib directory
    shutil.copy2(
            os.path.join(kw['source_dir'], 'lib', 'jslint.js'),
            os.path.join(kw['build_dir'], 'jslint.js'))


    return kw

def jq_form_before_hook(**kw):
    shutil.copytree(
            os.path.join(kw['source_dir']),
            kw['build_dir'])
    return kw

def plone_before_hook(**kw):
    for script in kw['plone_mapping']:
        if not script.startswith(kw['name']):
            continue
        script_path = os.path.join(kw['plone_dir'], script)
        if os.path.exists(script_path):
            f = open(script_path, 'w+')
            f.write('')
            f.close()
        if script_path.endswith('.js'):
            script_path = script_path[0:-3] + '.min.js'
            f = open(script_path, 'w+')
            f.write('')
            f.close()

    # FIXME: probably a better way to do this
    if os.path.exists(os.path.join(kw['source_dir'], 'test', 'dateinput', 'skin1.css')):
        shutil.copy(
            os.path.join(kw['source_dir'], 'test', 'dateinput', 'skin1.css'),
            os.path.join(kw['build_dir'], 'dateinput'))
    return kw

def version_hook(**kw):
    if not kw['filename'].endswith('.js') or \
       kw['filename'].endswith('jslint.js'):
        return kw
    args_ = shlex.split('sed -i -e "s/@VERSION/%(version)s/g" %(filename)s' % kw)
    subprocess.check_call(args_)
    return kw

def date_hook(**kw):
    if not kw['filename'].endswith('.js') or \
       kw['filename'].endswith('jslint.js'):
        return kw
    # FIXME: should be date from git log
    args_ = shlex.split('sed -i -e "s/@DATE/%(today)s/g" %(filename)s' % kw)
    subprocess.check_call(args_)
    return kw

def lint_hook(**kw):
    if not kw['filename'].endswith('.js') or \
       kw['filename'].endswith('jslint.js'):
        return kw
    # lint (http://www.jslint.com/lint.html)
    output = subprocess.Popen(
            shlex.split('java -jar %(rhino)s %(jslint)s %(filename)s ' % kw),
            stdout=subprocess.PIPE).communicate()
    if output[0].startswith('jslint: No problems found in'):
        print '  |-> jslint status: OK'
    else:
        print '  |-> jslint status: ERROR'
        print '\n'.join([(' '*6)+i for i in output[0].split('\n')])
    return kw

def minify_hook(**kw):
    if not kw['filename'].endswith('.js') or \
       kw['filename'].endswith('jslint.js'):
        return kw
    # minify with Closure Compiler (default mode)
    custom_kw = kw
    custom_kw['output_file'] = kw['filename'][:-3] + '.min.js'
    subprocess.check_call(
        shlex.split('java -jar %(compiler)s '
                    '--js %(filename)s '
                    '--js_output_file %(output_file)s' % custom_kw))
    print '  |-> minified to: ' + kw['short_filename'][:-3] + '.min.js'
    return kw

def plone_file_hook(**kw):
    if (not kw['filename'].endswith('.js') and \
        not kw['filename'].endswith('.css')) or \
       kw['filename'].endswith('jslint.js'):
        return kw
    for script in kw['plone_mapping']:
        if kw['name'] + ':' + kw['short_filename'] in kw['plone_mapping'][script]:
            build_filename = os.path.join(kw['plone_dir'], script)
            if kw['filename'].endswith('.js'):
                source_filename = os.path.join(kw['build_dir'], kw['short_filename'][:-3] + '.js')
            else:
                source_filename = os.path.join(kw['build_dir'], kw['short_filename'])

            g = open(source_filename)
            content = g.read()+'\n'
            g.close()

            f = open(build_filename, 'a+')
            f.write(content)
            f.close()

            print '  |-> plone: ' + build_filename[len(kw['plone_dir']) + 1:]

            if kw['filename'].endswith('.js'):
                # also do .min.js
                source_filename = os.path.join(kw['build_dir'], kw['short_filename'][:-3] + '.min.js')

                g = open(source_filename)
                content = g.read()+'\n'
                g.close()

                build_filename = build_filename[:-3] + '.min.js'
                f = open(build_filename, 'a+')
                f.write(content)
                f.close()

                print '  |-> plone: ' + build_filename[len(kw['plone_dir']) + 1:]
    return kw


if __name__ == '__main__':
    main()
